name: kendama
channels:
  - conda-forge
dependencies:
  - python
  - altair
  - vl-convert-python
  - jupyterlab
  - pandas
  - anywidget
  - shiny
  - shinywidgets
  - pymongo
  - pip
  - pip:
    - querychat
    - chatlas
    - python-dotenv
    - shinyswatch
